version: '3.1'

services:
  web:
    image: fast_api_imagev2
    # depends_on:
    #   - db
    ports:
      - 4000:80
    volumes:
      - ./app:/app
    # command: sh -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload "
  # db:
  #   image: mysql
  #   ports:
  #     - 3307:3306
  #   volumes:
  #     - ./app/db:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=adminPass